[package]
name = "achbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
log = "0.4.17"
simple_logger = "2.1.0"
linked-hash-map = "0.5.6"
subprocess = "0.2.9"
