on: [push]

name: CI

jobs:
  check:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: set up stable rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: check format
        with:
          command: fmt
          args: --check
